version: "3"

services:
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/srv
    working_dir: /srv
    command: bin/console start:kernel

  app:
    build:
      context: .
      args:
        - PHP_VERSION=8.3
      dockerfile: .boing/docker/app/symfony/Dockerfile
    ports:
      - 8000:80
    volumes:
      - .:/srv
