version: "3"

services:
  app:
    build:
      context: .
      args:
        - PHP_VERSION=8.3
      dockerfile: .boing/docker/app/symfony/Dockerfile
    ports:
      - 8000:80
    volumes:
      - .:/srv
